name: Apps
on: [workflow_dispatch]
permissions:
  id-token: write
  contents: read
jobs:
  create:
    environment: Azure
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate
      - run: terraform apply -auto-approve
      - run: terraform show
      - run: az aks get-credentials --resource-group rg-aks-prod-001 --name aks-demo
      - run: kubectl apply -f azure-vote.yaml
      - run: sleep 20
      - run: kubectl get service azure-vote-front